// Embed dist/engine.wasm as base64 into frontend/js/engine-wasm.js so the
// page runs from file:// (no fetch/CORS needed). Run by build.sh.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const wasm = fs.readFileSync(path.join(root, 'dist', 'engine.wasm'));
const b64 = wasm.toString('base64');
const out =
  '// AUTO-GENERATED by build.sh - base64 of dist/engine.wasm. Do not edit.\n' +
  'globalThis.CHESS_WASM_BASE64 = "' + b64 + '";\n';
fs.writeFileSync(path.join(root, 'frontend', 'js', 'engine-wasm.js'), out);
console.log('Wrote frontend/js/engine-wasm.js (' + b64.length + ' base64 chars)');
